config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  get "/", to: "static_pages#index"
  get "/instructions", to: "static_pages#instructions"
  get "/about", to: "static_pages#about"
  get "/packs", to: "pack_viewer#overview"
  get "/pack/:name", to: "pack_viewer#show_pack"
  get "/game/:name", to: "game#game"
  post "/game", to: "game#game"
  post "/game/create"
  delete "/game/leave"
  delete "/game/kick"
  post "/game/play_card"
  post "/game/select_card"
  post "/game/players", to: "game#get_players"
  post "/game/cards", to: "game#get_cards"
  post "/static_pages/games", to: "static_pages#get_games"
  patch "/set_nick", to: "game#set_nick"
end

app/models/game.rb
class Game < ActiveRecord::Base
  include BCrypt

  validates :name, {presence: true, uniqueness: true, length: (1..50)}

  # this is a horrible implementation, and should definitely never have seen the light
  # please look away before your eyes burn away, and you slowly transform into a puddle of sorrow and depression
  store :settings, accessors: [:black_card, :players, :host,
                               :card_czar, :packs, :decks,
                               :round, :scores, :last_kicked,
                               :last_winner, :last_nick_change], coder: JSON

  DECK_SIZE = 8

  #Tyler the
  def create(creator, requested_packs)
    # throw error if the game isn't valid according to model
    raise "Game is not valid" if !self.valid?
    self.host = self.card_czar = creator
    self.players = [creator]
    self.last_winner = []
    self.decks = self.round = self.scores = {}
    self.last_nick_change = ["", ""]
    self.last_kicked = nil
    self.save!

    determine_packs(requested_packs)

    update_players(creator)
  end

  # add all vars to new user
  def update_players(id=nil)
    # only add if it's not there already
    self.players << id if !self.players.include?(id) if id

    self.players.each do |p|
      self.decks[p] ||= []
      self.round[p] ||= []
      self.scores[p] ||= 0
    end

    self.save

    # don't distribute if no player is specified
    distribute_cards if (self.decks[id].empty? rescue false)

    if ready_for_next_round?
      new_round
    end
  end

  def delete_player(id)
    self.players.delete(id)
    self.decks.delete(id)
    self.round.delete(id)
    self.scores.delete(id)

    if self.card_czar == id and self.players.length > 1
      self.card_czar = self.players.sample
      new_round
    end

    self.host = self.players.first if self.host == id

    self.save!

    self.delete if self.players.length == 0

    return self.players.include?(id) ? false : true
  end

  def new_round
    self.black_card = nil
    self.save
    get_black_card
    self.round.keys.each { |k| self.round[k] = [] }
    distribute_cards
    self.card_czar = self.players[self.players.index(self.card_czar).next] || self.players[0]
    self.save
  end

  def play_card(player, card)
    # if user doesn't exist
    return nil if !self.players.include? player
    # if user doesn't have card
    return nil if !self.decks[player].include? card

    self.round[player] << card
    # only remove first entry, in case of multiple of same card
    self.decks[player].delete_at(self.decks[player].index(card))

    self.save

    return true
  end

  def select_card(cards, from_player)
    cards.each { |c| raise if !self.round[from_player].include? c }
    self.scores[from_player] += 1
    self.last_winner = cards
    self.save
    new_round
  end

  # has everyone done what they should do?
  def ready_for_next_round?
    # waiting_for_players returns a list of names
    waiting_for_players.size == 0
  end

  # deal a new black card
  def get_black_card
    if self.black_card.nil? or ready_for_next_round?
      self.black_card = Card.get_by_pack(self.packs)[:black].sample.id
    end

    self.save!

    return Card.where("id=?", self.black_card).first
  end

  def determine_packs(requested_packs)
    available_packs = Card.available_packs

    self.packs = requested_packs.to_a.reject do |x|
      x.last == "0" or !available_packs.include? x.first
    end.map { |x| x[0] } # only return the name, not the checked (1 or 0)

    if self.packs.nil? or self.packs.empty?
      self.packs = [Card.available_packs.sample]
    end

    cards_to_be = -> {Card.get_by_pack(self.packs)}

    self.packs << Card.available_packs.sample until cards_to_be.call[:white].length != 0 and cards_to_be.call[:black].length != 0

    self.save!
  end

  def distribute_cards
    self.players.each do |player|
      loop do
        # if the player somehow has more than the requested amount of cards
        if self.decks[player].length > DECK_SIZE
          self.decks[player].pop until self.decks[player] == DECK_SIZE
        end
        # if filled up
        break if self.decks[player].size == DECK_SIZE
        new_card = Card.get_by_pack(self.packs)[:white].sample.text
        self.decks[player] << new_card if !self.decks[player].include?(new_card)
      end
    end

    self.save!
  end

  def waiting_for_players
    self.round.reject do |k, v|
      # where played cards = cards required to be picked by black card
      v.length == (Card.where("id=?", self.black_card).first.pick rescue 0)
    end.keys # only return names
  end

  def migrate_nick(from, to)
    update_players(to)

    self.decks[to] = self.decks[from]
    self.round[to] = self.round[from]
    self.scores[to] = self.scores[from]

    # migrate states from old player
    self.host = to if self.host == from
    self.card_czar = to if self.card_czar == from
    self.last_kicked = to if self.last_kicked == from

    self.last_nick_change = [from, to]

    self.save!

    delete_player(from)
  end

  # Authentication and setting password
  def password=(password)
    self.password_digest = Password.create(password)
  end

  def authenticate(password)
    return self if password_digest.present? && Password.new(password_digest) == password
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :gen_identity
  before_action :get_current_game, except: [:create]
  before_action :authenticate, only: [:game]
  before_action :redir_if_kicked, except: [:create, :set_nick]

  def game
    if @game.last_kicked == session[:identity] && !@game.players.include?(session[:identity])
      @game.last_kicked = nil
      @game.save
      flash[:alert] = 'You were kicked from the game.'
      return redirect_to root_url
    end
    @game.create(session[:identity], nil) if @game.host.nil?
    @game.update_players(session[:identity])
    @game.save
    return redirect_to controller: 'game', action: 'game', name: @game.name if request.request_method == 'POST'
  end

  def create
    begin
      new_game = Game.new(params.permit(:name, :password))
      new_game.create(session[:identity], params[:pack])
      flash[:notice] = 'Game created.'
      session[:password_digest] = new_game.password_digest
      redirect_to controller: 'game', action: 'game', name: new_game.name
    rescue
      flash[:alert] = 'Game creation failed.'
      redirect_to root_url
    end
  end

  def leave
    begin
      raise if !@current_game.delete_player(params[:id])
      flash[:notice] = "Left game \"#{@current_game.name}\"."
    rescue
      flash[:alert] = 'Could not leave game.'
    end

    redirect_to root_url
  end

  def kick
    if @current_game.host == session[:identity]
      begin
        @current_game.delete_player(params[:player])
        @current_game.last_kicked = params[:player]
        @current_game.save!
        flash[:notice] = "Kicked player #{params[:player]}"
      rescue
        flash[:alert] = "Player doesn't exist"
      end
    else
      flash[:alert] = "You're not authorized to perform that action."
    end

    respond_to do |format|
      format.html { redirect_to action: 'game', name: @current_game.name }
      format.js
    end
  end

  def select_card
    if @current_game.card_czar == session[:identity] && @current_game.waiting_for_players.length == 1
      begin
        @current_game.select_card(JSON.parse(params[:cards]), params[:from])
      rescue
        flash[:alert] = "Could not award point for \"#{params[:cards]}\""
      end
    else
      flash[:alert] = 'Could not select card'
    end

    respond_to do |format|
      format.html { redirect_to action: 'game', name: params[:name] }
      format.js
    end
  end

  def play_card
    @game = @current_game
    if session[:identity] != params[:player]
      flash[:alert] = 'That is not your card. You broke something.'
    elsif session[:identity] == @current_game.card_czar
      flash[:alert] = "You're the card czar."
    elsif !@current_game.waiting_for_players.include? params[:player]
      flash[:alert] = 'You have played all cards required this round'
    else
      if !@current_game.play_card(params[:player], params[:card])
        flash[:alert] = 'Error while playing card.'
      end
    end

    respond_to do |format|
      format.html { redirect_to action: 'game', name: params[:name] }
      format.js
    end
  end

  def get_players
    @game = @current_game

    respond_to do |format|
      format.html { render plain: @game.players }
      format.js
    end
  end

  def get_cards
    @game = @current_game
    respond_to do |format|
      format.js
    end
  end

  def set_nick
    # remove special chars and limit length
    req_nick = params[:nick].gsub(/[^\w\s]/, '')[0...50] rescue ''

    if req_nick.empty?
      flash[:alert] = 'Requested nick can not be empty'
      return respond_to { |format| format.js }
    end

    if @current_game.players.include? req_nick
      flash[:alert] = 'That nickname is already in use'
    else
      @current_game.migrate_nick(session[:identity], req_nick)
      session[:identity] = req_nick
    end

    return respond_to { |format| format.js }
  end

  private

  def redir_if_kicked
    if @current_game.last_kicked == session[:identity] && !@current_game.players.include?(session[:identity])
      @current_game.last_kicked = nil
      @current_game.save
      flash[:alert] = 'You were kicked from the game.'
      return render js: "window.location = '#{root_url}'"
    end
  end

  def get_current_game
    req_game = params[:name] || params[:game][:name]
    @current_game ||= Game.where('name=?', req_game).first rescue nil
  end

  def gen_identity
    session[:identity] ||= Faker::Name.name
  end

  def authenticate
    authenticate_game = Game.where('name=?', params[:name]).first

    begin
      @game = authenticate_game.authenticate(params[:password])
      if !@game
        @game = authenticate_game if authenticate_game.password_digest == session[:password_digest]
      end
      raise if !@game
      session[:password_digest] = @game.password_digest
    rescue
      flash[:alert] = 'Wrong password'
      return redirect_to root_url
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/_czar_card.html.erb
<% for player in round %>
  <% if (!player[1].empty? rescue false) %>
  <%= form_for(@game, url: {action: "select_card"}, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :name, @game.name %>
  <%= hidden_field_tag :from, player[0] %>
  <%= hidden_field_tag :cards, player[1].to_json %>
  <% player[1].each do |card| %>
  <div data-player="<%= player[0] %>" class="col-xs-12 col-sm-4 col-lg-3 clearfix <%= 'inactive-' if session[:identity] != @game.card_czar %>player-card-set">
    <div class="square white-card" data-player="<%= player[0] %>">
      <div class="content">
        <p class="card-title"><%= raw card %></p>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
  <% end %>
<% end %>

app/views/game/_game_modal.html.erb
<div class="modal" role="dialog" aria-labelledby="game-modal" id="game-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag(controller: "game", action: "create") do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="game-create">Create a new game</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= label_tag :name %>
          <%= text_field_tag :name, nil, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag :password %>
          <%= password_field_tag :password, nil, class: "form-control" %>
          <small>* leave blank for no password-protection</small>
        </div>
        <hr>
        <div class="form-group">
          <% @packs.each do |pack| %>
            <div class="form-group checkbox">
              <label>
                <%= check_box :pack, pack %> <%= pack %>
              </label>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Create new game", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/game/_game_preview.html.erb
<div class="game-preview col-xs-12 col-sm-6 col-lg-4">
  <div class="well" data-protected='<%= game.authenticate("") ? "false" : "true" %>'>
    <%= form_tag(controller: "game", action: "game") do |f| %>
    <div class="game-preview-info">
      <h4><%= game.name %></h4>
      <p>
         <%= raw "<span class='small label label-danger'>password protected</span>" if !game.authenticate("") %>
         <span class="label label-default small player-count"><%= pluralize(game.players.length, "player") %></span>
      <span class="label label-primary small"><%= pluralize(game.packs.length, "pack") %></span>
      </p>
    </div>
    <div class="game-preview-form collapse">
        <%= hidden_field_tag :name, game.name %>
        <% if game.authenticate("") %>
        <%= hidden_field_tag :password, "" %>
        <% else %>
        <div class="input-group">
          <%= password_field_tag :password, nil, placeholder: "password", class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "Enter", class: "btn btn-default" %>
          </span>
        </div>
        <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/game/_nick_modal.html.erb
<div class="modal" role="dialog" aria-labelledby="nick-modal" id="nick-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag(set_nick_path, method: :patch, remote: true) do |f| %>
      <%= hidden_field_tag :name, (@game.name rescue '') %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="game-create">Change Nick</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= label_tag :nick %>
          <%= text_field_tag :nick, session[:identity], class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag "Save", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/game/_player.html.erb
<div class="col-sm-6 col-md-4">
  <div class="player well clearfix" data-player="<%= player %>">
    <div class="info"><p class="player-name"><%= raw player == session[:identity] ? "<a data-toggle='modal' data-target='#nick-modal'><span class='glyphicon glyphicon-pencil small'></span></a> <b>#{player}</b>" : player %></p>
      <span class="label label-default"><%= pluralize(@game.scores[player], "point") %></span>
      <% if @game.card_czar != player %>
        <% if @game.waiting_for_players.include? player %>
          <span class="label label-danger">not ready</span>
        <% else %>
          <span class="label label-success">ready</span>
        <% end %>
      <% elsif @game.card_czar == player and @game.waiting_for_players.length == 1 %>
        <span class="label label-danger">selecting</span>
      <% end %>
      <span class="label label-success"><%= "host" if player == @game.host %></span>
      <span class="label label-info"><%= "card czar" if player == @game.card_czar %></span>
    </div>
    <% if player != session[:identity] && @game.host == session[:identity] %>
      <%= form_for(@game, url: {action: "kick"}, method: :delete, remote: true) do |f| %>
        <%= hidden_field_tag :player, player %>
        <%= hidden_field_tag :name, @game.name %>
        <%= f.submit "Kick", class: "btn btn-warning" %>
      <% end %>
    <% elsif player == session[:identity] %>
      <%= form_for(@game, url: {action: "leave"}, method: :delete) do |f| %>
      <%= f.hidden_field :name %>
      <%= hidden_field_tag :id, session[:identity] %>
      <%= f.submit "Leave", class: "btn btn-warning" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/game/_white_card.html.erb
<div class="col-xs-6 col-sm-4 col-lg-2 clearfix">
  <%= form_for(@game, url: {action: "play_card"}, method: :post, remote: true) do |f| %>
    <div data-card="<%= raw card.text rescue card %>"
         class="square <%= card.pick.nil? ? "white" : "black" rescue "white" %>-card
                       <%= "inactive-" if !@game.waiting_for_players.include?(session[:identity]) ||
                                          session[:identity] == @game.card_czar %>game-card">
      <div class="content">
        <p class="card-title"><%= raw card.text rescue raw card %></p>
        <%= hidden_field_tag :player, session[:identity] %>
        <%= hidden_field_tag(:card, (card.text rescue card)) %>
        <%= hidden_field_tag :name, @game.name %>
      </div>
    </div>
  <% end %>
</div>

app/views/game/game.html.erb
<%= render partial: "nick_modal" %>

<h1><%= @game.name %></h1>
<hr/>
<div class="players row">
  <%= form_for(@game, url: {action: "get_players"}, method: :post, remote: true) do |f| %>
    <%= f.hidden_field :name %>
  <% end %>
  <%= render partial: "game/player", collection: @game.players %>
</div>
<%= form_for(@game, url: {action: "get_cards"}, method: :post, remote: true) do |f| %>
  <%= f.hidden_field :name %>
<% end %>
<hr/>
<div class="row black-and-played">
  <%= render partial: "pack_viewer/card", object: @game.get_black_card, as: :card %>
  <div class="played-cards clearfix col-xs-6 col-sm-8 col-lg-9">
  <%= render partial: "game/czar_card",
      object: @game.round,
      as: :round %>
  </div>
</div>
<hr/>
<div class="row white-cards">
  <%= render partial: "game/white_card",
             collection: @game.decks[session[:identity]],
             as: :card %>
</div>

app/views/game/get_cards.js.erb
// RUBY VARIABLE ASSIGNMENT
var black_card = $('.black-card .card-title').text();
var ruby_black_card = "<%= j @game.get_black_card.text %>";
var ruby_own_cards_played = "<%= j render partial: 'game/czar_card', object: {session[:identity]=>@game.round[session[:identity]]}, as: :round %>";
var ruby_played_cards = "<%= j render partial: 'game/czar_card', object: @game.round, as: :round %>";
var show_cards_played = "<%= @game.waiting_for_players.length == 1 %>" == "true";
var ruby_deck = <%= raw @game.decks[session[:identity]].as_json %>;
var ruby_deck_partial = "<%= j render partial: 'game/white_card', collection: @game.decks[session[:identity]], as: :card %>";
var ruby_cards_displayed = "<%= j @game.round.values.flatten.join '' %>";
var ruby_cards_played_players = <%= raw @game.round.keys.reject{|p|@game.round[p].length == 0}.as_json %>;
// END RUBY VARIABLE ASSIGNMENT

// CARDS PLAYED
var cards_displayed = $('.played-cards .card-title').text();
var cards_played_players = $('.played-cards .card-title').map(function () {
  return $(this).closest("[data-player]").data('player');
});

if (ruby_played_cards == "" && cards_displayed != ruby_cards_displayed) {
  $('.played-cards').html("");
} else if (show_cards_played == true && (cards_displayed != ruby_cards_displayed || ruby_cards_played_players.toString() != cards_played_players.toArray().toString())) {
  $('.played-cards').html(ruby_played_cards);
} else if (show_cards_played == false && ruby_own_cards_played != "" && cards_displayed != ruby_cards_displayed) {
  $('.played-cards').html(ruby_own_cards_played);
}
// END CARDS PLAYED

// DECK
var deck = $('.white-cards').children().children().children('div').map(function (i, elem) {
  return $(elem).data('card');
});

if (deck.toArray().toString() != ruby_deck.toString() ||
    black_card != ruby_black_card ||
    $('.white-cards input[name="player"]').first().val() != "<%= raw session[:identity] %>" ||
    $($.parseHTML(ruby_deck_partial)).find(".inactive-game-card").length != $('.inactive-game-card').length) {
  $('.white-cards').html(ruby_deck_partial);
}
// END DECK

// BLACK CARD
if (black_card != ruby_black_card) {
  $('.black-card').parent().remove();
  $('.black-and-played').prepend("<%= j render partial: '/pack_viewer/card', object: @game.get_black_card, as: :card %>").children('.black-card');
}
// END BLACK CARD

// apparently you need to redo this everytime you create .player-card-set elements
submitOnClick('.game-card,.player-card-set');

app/views/game/get_players.js.erb
var new_players = "<%= j render partial: '/game/player', collection: @current_game.players, as: :player %>";

var czar = null,
    host = null;

var players = [];

function getPlayerRoles () {
  $(".players .player").each(function (i, e) {
    if ($(e).css('display') != "none") {
      if ($(e).html().match('card czar')) {
        czar = $(e).data('player');
      }

      if ($(e).html().match('host')) {
        host = $(e).data('player');
      }

      players.push($(e).data('player'));
    }
  });
}

var player_scores = [];

function getScores () {
  player_scores = [];

  $(".players .player").each(function (i, e) {
    player_scores.push(Number($(e).html().match(/(\d+) points?/)[1]));
  });
}

var waiting_for_players = [];

function getWaitingForPlayers () {
  $('.player').each(function (i, e) {
    $(e).children('div.info').children('span.label').each(function (_i, _e) {
      if ($(_e).text() == "not ready") {
        waiting_for_players.push($(e).children('div.info').children('.player-name').text());
      }
    });
  });
}

var ruby_players = <%= raw @game.players.as_json %>;
var ruby_czar    = "<%= j @game.card_czar %>";
var ruby_host    = "<%= j @game.host %>";
var ruby_scores  = <%= raw @game.scores.values.to_json %>;
var ruby_waiting_for_players = <%= raw @game.waiting_for_players.reject { |p| p == @game.card_czar }.as_json %>;
var last_winner = "<%= j @game.last_winner.join("\", \"") %>";
var last_nick_change = <%= raw @game.last_nick_change.as_json %>;

getWaitingForPlayers();
getPlayerRoles();
getScores();

console.log(last_nick_change);

// flash for joining player
$(ruby_players).each(function (i, e) {
  if (players.indexOf(e) == -1 && last_nick_change.indexOf(e) == -1) {
    showFlash("notice", e + " has joined the game.");
  }
});

// flash leaving player
$(players).each(function (i, e) {
  if (ruby_players.indexOf(e) == -1 && last_nick_change.indexOf(e) == -1) {
    showFlash("notice", e + " has left the game.");
  }
});

// flashes for scores increasing
$(ruby_scores).each(function (i, e) {
  if (e != last_nick_change[0]) { // don't try to show awarded point because of "new user"
    if (player_scores[i] != e && '<%= session[:identity] %>' == players[i]) {
      showFlash("success", "You were awarded a point for \"" + last_winner + "\"!")
    } else if (player_scores[i] != e && e >= 1) {
      showFlash("notice", players[i] + " was awarded a point for \"" + last_winner + "\".")
    }
  }
});

// Array comparison is completely retarded in JavaScript,
// so we'll convert the arrays to strings for comparison
if (ruby_players.toString() != players.toString() ||
    host != ruby_host ||
    czar != ruby_czar ||
    waiting_for_players.toString() != ruby_waiting_for_players.toString()) {
  form = $('.players').children()[0];
  $('.players').html(new_players).prepend(form);
}

app/views/game/kick.js.erb
<% flash.keys.each do |f| %>
  showFlash("<%= j f %>", "<%= j flash[f] %>");
<% end %>

$('[data-player="<%= params[:player] %>"]').fadeOut(function () {
  $(this).closest("[class *= 'col-']").remove();
});

app/views/game/play_card.js.erb
<% flash.keys.each do |f| %>
  showFlash("<%= j f %>", "<%= j flash[f] %>");
<% end %>

var ruby_card_played = <%= raw params[:card].inspect %>;

var ruby_own_cards_played = "<%= j render partial: 'game/czar_card', object: {session[:identity]=>@game.round[session[:identity]]}, as: :round %>";

// show card played
$('.played-cards').html(ruby_own_cards_played);

$('.white-cards').children().children().children('div').each(function (i, e) {
  if (ruby_card_played == $(e).data('card')) {
    <% if !flash[:alert] %>
      // fade out and remove
      $(e).parent().parent().remove();
    <% end %>
  }
});

app/views/game/select_card.js.erb
<% flash.keys.each do |f| %>
  showFlash("<%= j f %>", "<%= j flash[f] %>");
<% end %>

submitForms();

app/views/game/set_nick.js.erb
<% flash.keys.each do |f| %>
  showFlash("<%= j f %>", "<%= j flash[f] %>");
<% end %>

$('#nick-modal .close').click();

submitForms();